# Generated by Django 6.0.1 on 2026-01-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
