# Generated by Django 6.0.1 on 2026-01-24 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_shipment_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='quantity',
        ),
    ]
